name: Zotero update

on:
  schedule:
    - cron:  '0 9,17 * * *'
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  zoteropull:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Python Script
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.7' 
        cache: 'pip'
      run: pip install -r _bibliography/requirements.txt
      run: python _bibliography/zotjek.py
      shell: sh
  deploy:
    needs: zoteropull
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.1'
        bundler-cache: true
    - name: Install and Build 🔧
      run: |
        npm install -g mermaid.cli
        bundle exec jekyll build
    - name: Deploy 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site

