name: deploy

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9,17 * * *'

permissions:
  contents: write

jobs:
  zoteropull:
    runs-on: ubuntu-latest
    steps:
    - name: Python Script
      run: python _bibliography/zotjek.py
      shell: sh
  deploy:
    needs: zoteropull
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.1'
        bundler-cache: true
    - name: Install and Build 🔧
      run: |
        npm install -g mermaid.cli
        bundle exec jekyll build
    - name: Deploy 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site

